//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalCareSystem.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DentalCareSystem.Resources.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account updated..
        /// </summary>
        public static string AccountUpdated {
            get {
                return ResourceManager.GetString("AccountUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add appointment.
        /// </summary>
        public static string AddAppointment {
            get {
                return ResourceManager.GetString("AddAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new appointment.
        /// </summary>
        public static string AddAppointmentTitle {
            get {
                return ResourceManager.GetString("AddAppointmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new category.
        /// </summary>
        public static string AddCategoryTitle {
            get {
                return ResourceManager.GetString("AddCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new examination.
        /// </summary>
        public static string AddExaminationTitle {
            get {
                return ResourceManager.GetString("AddExaminationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new material.
        /// </summary>
        public static string AddMaterialTitle {
            get {
                return ResourceManager.GetString("AddMaterialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Employee.
        /// </summary>
        public static string AddNewEmployee {
            get {
                return ResourceManager.GetString("AddNewEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Patient.
        /// </summary>
        public static string AddNewPatient {
            get {
                return ResourceManager.GetString("AddNewPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new treatment.
        /// </summary>
        public static string AddNewTreatment {
            get {
                return ResourceManager.GetString("AddNewTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new patient.
        /// </summary>
        public static string AddPatientTitle {
            get {
                return ResourceManager.GetString("AddPatientTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All appointments loaded..
        /// </summary>
        public static string AllAppointmentsLoaded {
            get {
                return ResourceManager.GetString("AllAppointmentsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All dentists.
        /// </summary>
        public static string AllDentists {
            get {
                return ResourceManager.GetString("AllDentists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All examinations loaded..
        /// </summary>
        public static string AllExaminationsLoaded {
            get {
                return ResourceManager.GetString("AllExaminationsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All roles.
        /// </summary>
        public static string AllRoles {
            get {
                return ResourceManager.GetString("AllRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already added.
        /// </summary>
        public static string AlreadyAdded {
            get {
                return ResourceManager.GetString("AlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment added..
        /// </summary>
        public static string AppointmentAdded {
            get {
                return ResourceManager.GetString("AppointmentAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment date.
        /// </summary>
        public static string AppointmentDate {
            get {
                return ResourceManager.GetString("AppointmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment found..
        /// </summary>
        public static string AppointmentFound {
            get {
                return ResourceManager.GetString("AppointmentFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string AppointmentId {
            get {
                return ResourceManager.GetString("AppointmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment not found..
        /// </summary>
        public static string AppointmentNotFound {
            get {
                return ResourceManager.GetString("AppointmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments.
        /// </summary>
        public static string Appointments {
            get {
                return ResourceManager.GetString("Appointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment selected..
        /// </summary>
        public static string AppointmentSelected {
            get {
                return ResourceManager.GetString("AppointmentSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment selection.
        /// </summary>
        public static string AppointmentSelection {
            get {
                return ResourceManager.GetString("AppointmentSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment time slot is already taken for the selected dentist.
        /// </summary>
        public static string AppointmentTimeTaken {
            get {
                return ResourceManager.GetString("AppointmentTimeTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment updated..
        /// </summary>
        public static string AppointmentUpdated {
            get {
                return ResourceManager.GetString("AppointmentUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below the minimum.
        /// </summary>
        public static string BelowMin {
            get {
                return ResourceManager.GetString("BelowMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill.
        /// </summary>
        public static string Bill {
            get {
                return ResourceManager.GetString("Bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill number.
        /// </summary>
        public static string BillNumber {
            get {
                return ResourceManager.GetString("BillNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bills.
        /// </summary>
        public static string Bills {
            get {
                return ResourceManager.GetString("Bills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category added..
        /// </summary>
        public static string CategoryAdded {
            get {
                return ResourceManager.GetString("CategoryAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category deleted..
        /// </summary>
        public static string CategoryDeleted {
            get {
                return ResourceManager.GetString("CategoryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category .
        /// </summary>
        public static string CategoryFilter {
            get {
                return ResourceManager.GetString("CategoryFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category updated..
        /// </summary>
        public static string CategoryUpdated {
            get {
                return ResourceManager.GetString("CategoryUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose material and quantity.
        /// </summary>
        public static string ChooseMaterial {
            get {
                return ResourceManager.GetString("ChooseMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose material and quantity.
        /// </summary>
        public static string ChooseMaterial1 {
            get {
                return ResourceManager.GetString("ChooseMaterial1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Tooltip.
        /// </summary>
        public static string CloseTooltip {
            get {
                return ResourceManager.GetString("CloseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add a new patient?.
        /// </summary>
        public static string ConfirmAdd {
            get {
                return ResourceManager.GetString("ConfirmAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string ConfirmationTitle {
            get {
                return ResourceManager.GetString("ConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete?.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock - ascending.
        /// </summary>
        public static string CurrentStockAscending {
            get {
                return ResourceManager.GetString("CurrentStockAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock - descending.
        /// </summary>
        public static string CurrentStockDescending {
            get {
                return ResourceManager.GetString("CurrentStockDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date - ascending.
        /// </summary>
        public static string DateAscending {
            get {
                return ResourceManager.GetString("DateAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date - descending.
        /// </summary>
        public static string DateDescending {
            get {
                return ResourceManager.GetString("DateDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datetime.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Appointment.
        /// </summary>
        public static string DeleteAppointment {
            get {
                return ResourceManager.GetString("DeleteAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete record because there are related data..
        /// </summary>
        public static string DeleteNotAllowed {
            get {
                return ResourceManager.GetString("DeleteNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dentist.
        /// </summary>
        public static string Dentist {
            get {
                return ResourceManager.GetString("Dentist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dentist ID.
        /// </summary>
        public static string DentistJMBG {
            get {
                return ResourceManager.GetString("DentistJMBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dentist not found..
        /// </summary>
        public static string DentistNotFound {
            get {
                return ResourceManager.GetString("DentistNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dentists.
        /// </summary>
        public static string Dentists {
            get {
                return ResourceManager.GetString("Dentists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis.
        /// </summary>
        public static string Diagnosis {
            get {
                return ResourceManager.GetString("Diagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee added..
        /// </summary>
        public static string EmployeeAdded {
            get {
                return ResourceManager.GetString("EmployeeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee not found..
        /// </summary>
        public static string EmployeeNotFound {
            get {
                return ResourceManager.GetString("EmployeeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter appointment ID..
        /// </summary>
        public static string EnterAppointmentId {
            get {
                return ResourceManager.GetString("EnterAppointmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter diagnosis..
        /// </summary>
        public static string EnterDiagnosis {
            get {
                return ResourceManager.GetString("EnterDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error applying filter..
        /// </summary>
        public static string ErrorApplyingFilter {
            get {
                return ResourceManager.GetString("ErrorApplyingFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading categories..
        /// </summary>
        public static string ErrorLoadingCategories {
            get {
                return ResourceManager.GetString("ErrorLoadingCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error..
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error refreshing data..
        /// </summary>
        public static string ErrorRefreshingData {
            get {
                return ResourceManager.GetString("ErrorRefreshingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error searching dentist.
        /// </summary>
        public static string ErrorSearchingDentist {
            get {
                return ResourceManager.GetString("ErrorSearchingDentist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error searching employee..
        /// </summary>
        public static string ErrorSearchingEmployee {
            get {
                return ResourceManager.GetString("ErrorSearchingEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error searching medical technician.
        /// </summary>
        public static string ErrorSearchingMedicalTechnician {
            get {
                return ResourceManager.GetString("ErrorSearchingMedicalTechnician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error searching patient..
        /// </summary>
        public static string ErrorSearchingPatient {
            get {
                return ResourceManager.GetString("ErrorSearchingPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examination added..
        /// </summary>
        public static string ExaminationAdded {
            get {
                return ResourceManager.GetString("ExaminationAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examination already exists..
        /// </summary>
        public static string ExaminationAlreadyExists {
            get {
                return ResourceManager.GetString("ExaminationAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examination information.
        /// </summary>
        public static string ExaminationInformation {
            get {
                return ResourceManager.GetString("ExaminationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examinations.
        /// </summary>
        public static string Examinations {
            get {
                return ResourceManager.GetString("Examinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examination updated..
        /// </summary>
        public static string ExaminationUpdated {
            get {
                return ResourceManager.GetString("ExaminationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add category..
        /// </summary>
        public static string FailedToAddCategory {
            get {
                return ResourceManager.GetString("FailedToAddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all the fields..
        /// </summary>
        public static string FillFields {
            get {
                return ResourceManager.GetString("FillFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By Category.
        /// </summary>
        public static string FilterByItemCategory {
            get {
                return ResourceManager.GetString("FilterByItemCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter cleared..
        /// </summary>
        public static string FilterCleared {
            get {
                return ResourceManager.GetString("FilterCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered..
        /// </summary>
        public static string Filtered {
            get {
                return ResourceManager.GetString("Filtered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a date.
        /// </summary>
        public static string FilteredErrorDate {
            get {
                return ResourceManager.GetString("FilteredErrorDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For date.
        /// </summary>
        public static string ForDate {
            get {
                return ResourceManager.GetString("ForDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For dentist.
        /// </summary>
        public static string ForDentist {
            get {
                return ResourceManager.GetString("ForDentist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For dentist.
        /// </summary>
        public static string ForDentistJMBG {
            get {
                return ResourceManager.GetString("ForDentistJMBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For patient.
        /// </summary>
        public static string ForPatientJMBG {
            get {
                return ResourceManager.GetString("ForPatientJMBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRI.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string InfoTitle {
            get {
                return ResourceManager.GetString("InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials..
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format..
        /// </summary>
        public static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format..
        /// </summary>
        public static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid id format (jmbg)..
        /// </summary>
        public static string InvalidJmbgFormat {
            get {
                return ResourceManager.GetString("InvalidJmbgFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone format..
        /// </summary>
        public static string InvalidPhoneFormat {
            get {
                return ResourceManager.GetString("InvalidPhoneFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid price format..
        /// </summary>
        public static string InvalidPriceFormat {
            get {
                return ResourceManager.GetString("InvalidPriceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material added..
        /// </summary>
        public static string MaterialAdded {
            get {
                return ResourceManager.GetString("MaterialAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Category.
        /// </summary>
        public static string MaterialCategory {
            get {
                return ResourceManager.GetString("MaterialCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Stock.
        /// </summary>
        public static string MaterialCurrentStock {
            get {
                return ResourceManager.GetString("MaterialCurrentStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material deleted,.
        /// </summary>
        public static string MaterialDeleted {
            get {
                return ResourceManager.GetString("MaterialDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material adding error.
        /// </summary>
        public static string MaterialError {
            get {
                return ResourceManager.GetString("MaterialError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material error update.
        /// </summary>
        public static string MaterialErrorUpdate {
            get {
                return ResourceManager.GetString("MaterialErrorUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Stock.
        /// </summary>
        public static string MaterialMinStock {
            get {
                return ResourceManager.GetString("MaterialMinStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Name.
        /// </summary>
        public static string MaterialName {
            get {
                return ResourceManager.GetString("MaterialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string MaterialPrice {
            get {
                return ResourceManager.GetString("MaterialPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials.
        /// </summary>
        public static string Materials {
            get {
                return ResourceManager.GetString("Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string MaterialUnit {
            get {
                return ResourceManager.GetString("MaterialUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material updated..
        /// </summary>
        public static string MaterialUpdated {
            get {
                return ResourceManager.GetString("MaterialUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material warning.
        /// </summary>
        public static string MaterialWarning {
            get {
                return ResourceManager.GetString("MaterialWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical History.
        /// </summary>
        public static string MedicalHistory {
            get {
                return ResourceManager.GetString("MedicalHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Technician.
        /// </summary>
        public static string MedicalTechnician {
            get {
                return ResourceManager.GetString("MedicalTechnician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical technician not found..
        /// </summary>
        public static string MedicalTechnicianNotFound {
            get {
                return ResourceManager.GetString("MedicalTechnicianNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Technicians.
        /// </summary>
        public static string MedicalTechnicians {
            get {
                return ResourceManager.GetString("MedicalTechnicians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Box Title.
        /// </summary>
        public static string MessageBoxTitle {
            get {
                return ResourceManager.GetString("MessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MON.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Filter.
        /// </summary>
        public static string NameFilter {
            get {
                return ResourceManager.GetString("NameFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameSurname {
            get {
                return ResourceManager.GetString("NameSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No appointments found.
        /// </summary>
        public static string NoAppointmentsFound {
            get {
                return ResourceManager.GetString("NoAppointmentsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No employees found.
        /// </summary>
        public static string NoEmployeesFound {
            get {
                return ResourceManager.GetString("NoEmployeesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No examinations found..
        /// </summary>
        public static string NoExaminationsFound {
            get {
                return ResourceManager.GetString("NoExaminationsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No selected items..
        /// </summary>
        public static string NoSelection {
            get {
                return ResourceManager.GetString("NoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Tooltip.
        /// </summary>
        public static string NoTooltip {
            get {
                return ResourceManager.GetString("NoTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok Tooltip.
        /// </summary>
        public static string OkTooltip {
            get {
                return ResourceManager.GetString("OkTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string Patient {
            get {
                return ResourceManager.GetString("Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient added..
        /// </summary>
        public static string PatientAdded {
            get {
                return ResourceManager.GetString("PatientAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient found.
        /// </summary>
        public static string PatientFound {
            get {
                return ResourceManager.GetString("PatientFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient ID.
        /// </summary>
        public static string PatientID {
            get {
                return ResourceManager.GetString("PatientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient information.
        /// </summary>
        public static string PatientInformation {
            get {
                return ResourceManager.GetString("PatientInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient ID.
        /// </summary>
        public static string PatientJMBG {
            get {
                return ResourceManager.GetString("PatientJMBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient not found..
        /// </summary>
        public static string PatientNotFound {
            get {
                return ResourceManager.GetString("PatientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients.
        /// </summary>
        public static string Patients {
            get {
                return ResourceManager.GetString("Patients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient updated..
        /// </summary>
        public static string PatientUpdated {
            get {
                return ResourceManager.GetString("PatientUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price - ascending.
        /// </summary>
        public static string PriceAscending {
            get {
                return ResourceManager.GetString("PriceAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price - descending.
        /// </summary>
        public static string PriceDescending {
            get {
                return ResourceManager.GetString("PriceDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshed..
        /// </summary>
        public static string Refreshed {
            get {
                return ResourceManager.GetString("Refreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All Filters.
        /// </summary>
        public static string RemoveAllFilters {
            get {
                return ResourceManager.GetString("RemoveAllFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAT.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchByID.
        /// </summary>
        public static string SearchByID {
            get {
                return ResourceManager.GetString("SearchByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select appointment.
        /// </summary>
        public static string SelectAppointment {
            get {
                return ResourceManager.GetString("SelectAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select bill to view.
        /// </summary>
        public static string SelectBillToView {
            get {
                return ResourceManager.GetString("SelectBillToView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select medical technician.
        /// </summary>
        public static string SelectMedicalTechnician {
            get {
                return ResourceManager.GetString("SelectMedicalTechnician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select role.
        /// </summary>
        public static string SelectRole {
            get {
                return ResourceManager.GetString("SelectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian.
        /// </summary>
        public static string Serbian {
            get {
                return ResourceManager.GetString("Serbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing all materials..
        /// </summary>
        public static string ShowingAllMaterials {
            get {
                return ResourceManager.GetString("ShowingAllMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        public static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort cleared..
        /// </summary>
        public static string SortCleared {
            get {
                return ResourceManager.GetString("SortCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted..
        /// </summary>
        public static string Sorted {
            get {
                return ResourceManager.GetString("Sorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization.
        /// </summary>
        public static string Specialization {
            get {
                return ResourceManager.GetString("Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock .
        /// </summary>
        public static string StockFilter {
            get {
                return ResourceManager.GetString("StockFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted..
        /// </summary>
        public static string SuccessfullyDeleted {
            get {
                return ResourceManager.GetString("SuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sufficient stock.
        /// </summary>
        public static string Sufficient {
            get {
                return ResourceManager.GetString("Sufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUN.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surprise.
        /// </summary>
        public static string Surprise {
            get {
                return ResourceManager.GetString("Surprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THU.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total price.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment added..
        /// </summary>
        public static string TreatmentAdded {
            get {
                return ResourceManager.GetString("TreatmentAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatments.
        /// </summary>
        public static string Treatments {
            get {
                return ResourceManager.GetString("Treatments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment updated..
        /// </summary>
        public static string TreatmentUpdated {
            get {
                return ResourceManager.GetString("TreatmentUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TUE.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessfully deleted..
        /// </summary>
        public static string UnsuccessfullyDeleted {
            get {
                return ResourceManager.GetString("UnsuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Appointment.
        /// </summary>
        public static string UpdateAppointment {
            get {
                return ResourceManager.GetString("UpdateAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update appointment.
        /// </summary>
        public static string UpdateAppointmentTitle {
            get {
                return ResourceManager.GetString("UpdateAppointmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update category.
        /// </summary>
        public static string UpdateCategoryTitle {
            get {
                return ResourceManager.GetString("UpdateCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update examination.
        /// </summary>
        public static string UpdateExaminationTitle {
            get {
                return ResourceManager.GetString("UpdateExaminationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update material.
        /// </summary>
        public static string UpdateMaterialTitle {
            get {
                return ResourceManager.GetString("UpdateMaterialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update patient.
        /// </summary>
        public static string UpdatePatientTitle {
            get {
                return ResourceManager.GetString("UpdatePatientTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update treatment.
        /// </summary>
        public static string UpdateTreatment {
            get {
                return ResourceManager.GetString("UpdateTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        public static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WED.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes Tooltip.
        /// </summary>
        public static string YesTooltip {
            get {
                return ResourceManager.GetString("YesTooltip", resourceCulture);
            }
        }
    }
}
