//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalCareSystem.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class sr_RS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sr_RS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DentalCareSystem.Resources.sr-RS", typeof(sr_RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nalog ažuriran..
        /// </summary>
        public static string AccountUpdated {
            get {
                return ResourceManager.GetString("AccountUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj termin.
        /// </summary>
        public static string AddAppointment {
            get {
                return ResourceManager.GetString("AddAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj novi termin.
        /// </summary>
        public static string AddAppointmentTitle {
            get {
                return ResourceManager.GetString("AddAppointmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj novu kategoriju.
        /// </summary>
        public static string AddCategoryTitle {
            get {
                return ResourceManager.GetString("AddCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj novi pregled.
        /// </summary>
        public static string AddExaminationTitle {
            get {
                return ResourceManager.GetString("AddExaminationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj novi materijal.
        /// </summary>
        public static string AddMaterialTitle {
            get {
                return ResourceManager.GetString("AddMaterialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj novog zaposlenog.
        /// </summary>
        public static string AddNewEmployee {
            get {
                return ResourceManager.GetString("AddNewEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj novog pacijenta.
        /// </summary>
        public static string AddNewPatient {
            get {
                return ResourceManager.GetString("AddNewPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj novi tretman.
        /// </summary>
        public static string AddNewTreatment {
            get {
                return ResourceManager.GetString("AddNewTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj novog pacijenta.
        /// </summary>
        public static string AddPatientTitle {
            get {
                return ResourceManager.GetString("AddPatientTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svi termini prikazani..
        /// </summary>
        public static string AllAppointmentsLoaded {
            get {
                return ResourceManager.GetString("AllAppointmentsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svi stomatolozi.
        /// </summary>
        public static string AllDentists {
            get {
                return ResourceManager.GetString("AllDentists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svi pregledi učitani..
        /// </summary>
        public static string AllExaminationsLoaded {
            get {
                return ResourceManager.GetString("AllExaminationsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sve uloge.
        /// </summary>
        public static string AllRoles {
            get {
                return ResourceManager.GetString("AllRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Već dodano.
        /// </summary>
        public static string AlreadyAdded {
            get {
                return ResourceManager.GetString("AlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izgled.
        /// </summary>
        public static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primijeni.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termin dodan..
        /// </summary>
        public static string AppointmentAdded {
            get {
                return ResourceManager.GetString("AppointmentAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum termina.
        /// </summary>
        public static string AppointmentDate {
            get {
                return ResourceManager.GetString("AppointmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termin pronađen..
        /// </summary>
        public static string AppointmentFound {
            get {
                return ResourceManager.GetString("AppointmentFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID .
        /// </summary>
        public static string AppointmentId {
            get {
                return ResourceManager.GetString("AppointmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termin nije pronađen..
        /// </summary>
        public static string AppointmentNotFound {
            get {
                return ResourceManager.GetString("AppointmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termini.
        /// </summary>
        public static string Appointments {
            get {
                return ResourceManager.GetString("Appointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termin slektovan..
        /// </summary>
        public static string AppointmentSelected {
            get {
                return ResourceManager.GetString("AppointmentSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabir termina.
        /// </summary>
        public static string AppointmentSelection {
            get {
                return ResourceManager.GetString("AppointmentSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termin je već zauzet za odabranog doktora.
        /// </summary>
        public static string AppointmentTimeTaken {
            get {
                return ResourceManager.GetString("AppointmentTimeTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termin ažuriran..
        /// </summary>
        public static string AppointmentUpdated {
            get {
                return ResourceManager.GetString("AppointmentUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ispod minimuma.
        /// </summary>
        public static string BelowMin {
            get {
                return ResourceManager.GetString("BelowMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Račun.
        /// </summary>
        public static string Bill {
            get {
                return ResourceManager.GetString("Bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj računa.
        /// </summary>
        public static string BillNumber {
            get {
                return ResourceManager.GetString("BillNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Računi.
        /// </summary>
        public static string Bills {
            get {
                return ResourceManager.GetString("Bills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traži.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorije.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorija dodana..
        /// </summary>
        public static string CategoryAdded {
            get {
                return ResourceManager.GetString("CategoryAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorija obrisana..
        /// </summary>
        public static string CategoryDeleted {
            get {
                return ResourceManager.GetString("CategoryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorija .
        /// </summary>
        public static string CategoryFilter {
            get {
                return ResourceManager.GetString("CategoryFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv kategorije.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorija ažurirana..
        /// </summary>
        public static string CategoryUpdated {
            get {
                return ResourceManager.GetString("CategoryUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite materijal i količinu.
        /// </summary>
        public static string ChooseMaterial {
            get {
                return ResourceManager.GetString("ChooseMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatvori.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatvori.
        /// </summary>
        public static string CloseTooltip {
            get {
                return ResourceManager.GetString("CloseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li želite da dodate novog pacijenta?.
        /// </summary>
        public static string ConfirmAdd {
            get {
                return ResourceManager.GetString("ConfirmAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrda.
        /// </summary>
        public static string ConfirmationTitle {
            get {
                return ResourceManager.GetString("ConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni da želite da obrišete?.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalihe - rastuće.
        /// </summary>
        public static string CurrentStockAscending {
            get {
                return ResourceManager.GetString("CurrentStockAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalihe - opadajuće.
        /// </summary>
        public static string CurrentStockDescending {
            get {
                return ResourceManager.GetString("CurrentStockDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamna.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum - rastuće.
        /// </summary>
        public static string DateAscending {
            get {
                return ResourceManager.GetString("DateAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum - opadajuće.
        /// </summary>
        public static string DateDescending {
            get {
                return ResourceManager.GetString("DateDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum i vrijeme.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izbriši.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije moguće obrisati zapis jer postoje povezani podaci..
        /// </summary>
        public static string DeleteNotAllowed {
            get {
                return ResourceManager.GetString("DeleteNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stomatolog.
        /// </summary>
        public static string Dentist {
            get {
                return ResourceManager.GetString("Dentist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMBG Stomatologa.
        /// </summary>
        public static string DentistJMBG {
            get {
                return ResourceManager.GetString("DentistJMBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stomatolog nije pronađen..
        /// </summary>
        public static string DentistNotFound {
            get {
                return ResourceManager.GetString("DentistNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stomatolozi.
        /// </summary>
        public static string Dentists {
            get {
                return ResourceManager.GetString("Dentists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dijagnoza.
        /// </summary>
        public static string Diagnosis {
            get {
                return ResourceManager.GetString("Diagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaposleni.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaposleni dodan..
        /// </summary>
        public static string EmployeeAdded {
            get {
                return ResourceManager.GetString("EmployeeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaposleni nije pronađen..
        /// </summary>
        public static string EmployeeNotFound {
            get {
                return ResourceManager.GetString("EmployeeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaposleni.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite ID termina..
        /// </summary>
        public static string EnterAppointmentId {
            get {
                return ResourceManager.GetString("EnterAppointmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite dijagnozu..
        /// </summary>
        public static string EnterDiagnosis {
            get {
                return ResourceManager.GetString("EnterDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška prilikom filtriranja..
        /// </summary>
        public static string ErrorApplyingFilter {
            get {
                return ResourceManager.GetString("ErrorApplyingFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška prilikom učitavanja kategorija..
        /// </summary>
        public static string ErrorLoadingCategories {
            get {
                return ResourceManager.GetString("ErrorLoadingCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška.
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška prilikom osvježavanja..
        /// </summary>
        public static string ErrorRefreshingData {
            get {
                return ResourceManager.GetString("ErrorRefreshingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška prilikom pretrage zaposlenih..
        /// </summary>
        public static string ErrorSearchingEmployee {
            get {
                return ResourceManager.GetString("ErrorSearchingEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška prilikom pretraživanja pacijenta..
        /// </summary>
        public static string ErrorSearchingPatient {
            get {
                return ResourceManager.GetString("ErrorSearchingPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled dodan..
        /// </summary>
        public static string ExaminationAdded {
            get {
                return ResourceManager.GetString("ExaminationAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled već postoji..
        /// </summary>
        public static string ExaminationAlreadyExists {
            get {
                return ResourceManager.GetString("ExaminationAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacije o pregledu.
        /// </summary>
        public static string ExaminationInformation {
            get {
                return ResourceManager.GetString("ExaminationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregledi.
        /// </summary>
        public static string Examinations {
            get {
                return ResourceManager.GetString("Examinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled ažuriran..
        /// </summary>
        public static string ExaminationUpdated {
            get {
                return ResourceManager.GetString("ExaminationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molim Vas popunite sva polja..
        /// </summary>
        public static string FillFields {
            get {
                return ResourceManager.GetString("FillFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtriraj po kategoriji.
        /// </summary>
        public static string FilterByItemCategory {
            get {
                return ResourceManager.GetString("FilterByItemCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter uklonjen..
        /// </summary>
        public static string FilterCleared {
            get {
                return ResourceManager.GetString("FilterCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtriran prikaz..
        /// </summary>
        public static string Filtered {
            get {
                return ResourceManager.GetString("Filtered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite datum za filtriranje.
        /// </summary>
        public static string FilteredErrorDate {
            get {
                return ResourceManager.GetString("FilteredErrorDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za datum.
        /// </summary>
        public static string ForDate {
            get {
                return ResourceManager.GetString("ForDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za stomatologa.
        /// </summary>
        public static string ForDentist {
            get {
                return ResourceManager.GetString("ForDentist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za stomatologa.
        /// </summary>
        public static string ForDentistJMBG {
            get {
                return ResourceManager.GetString("ForDentistJMBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za pacijenta.
        /// </summary>
        public static string ForPatientJMBG {
            get {
                return ResourceManager.GetString("ForPatientJMBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petak.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Od datuma.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMBG .
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacija.
        /// </summary>
        public static string InfoTitle {
            get {
                return ResourceManager.GetString("InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nevalidan format email-a..
        /// </summary>
        public static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nevalidan format..
        /// </summary>
        public static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nevalidan format jmbg-a..
        /// </summary>
        public static string InvalidJmbgFormat {
            get {
                return ResourceManager.GetString("InvalidJmbgFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nevalidan format broja telefona..
        /// </summary>
        public static string InvalidPhoneFormat {
            get {
                return ResourceManager.GetString("InvalidPhoneFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nevalidan format cijene..
        /// </summary>
        public static string InvalidPriceFormat {
            get {
                return ResourceManager.GetString("InvalidPriceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svijetla.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjavi se.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materijal dodan..
        /// </summary>
        public static string MaterialAdded {
            get {
                return ResourceManager.GetString("MaterialAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materijal kategorija.
        /// </summary>
        public static string MaterialCategory {
            get {
                return ResourceManager.GetString("MaterialCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutna zaliha.
        /// </summary>
        public static string MaterialCurrentStock {
            get {
                return ResourceManager.GetString("MaterialCurrentStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materijal obrisan..
        /// </summary>
        public static string MaterialDeleted {
            get {
                return ResourceManager.GetString("MaterialDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri dodavanju materijala.
        /// </summary>
        public static string MaterialError {
            get {
                return ResourceManager.GetString("MaterialError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri ažuriranju materijala.
        /// </summary>
        public static string MaterialErrorUpdate {
            get {
                return ResourceManager.GetString("MaterialErrorUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalna zaliha.
        /// </summary>
        public static string MaterialMinStock {
            get {
                return ResourceManager.GetString("MaterialMinStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv materijala.
        /// </summary>
        public static string MaterialName {
            get {
                return ResourceManager.GetString("MaterialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cijena.
        /// </summary>
        public static string MaterialPrice {
            get {
                return ResourceManager.GetString("MaterialPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materijali.
        /// </summary>
        public static string Materials {
            get {
                return ResourceManager.GetString("Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jedinica.
        /// </summary>
        public static string MaterialUnit {
            get {
                return ResourceManager.GetString("MaterialUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materijal ažuriran..
        /// </summary>
        public static string MaterialUpdated {
            get {
                return ResourceManager.GetString("MaterialUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upozorenje za materijal.
        /// </summary>
        public static string MaterialWarning {
            get {
                return ResourceManager.GetString("MaterialWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicinska istorija.
        /// </summary>
        public static string MedicalHistory {
            get {
                return ResourceManager.GetString("MedicalHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicinski tehničar.
        /// </summary>
        public static string MedicalTechnician {
            get {
                return ResourceManager.GetString("MedicalTechnician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicinski tehničar nije pronađen..
        /// </summary>
        public static string MedicalTechnicianNotFound {
            get {
                return ResourceManager.GetString("MedicalTechnicianNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicinski tehničari.
        /// </summary>
        public static string MedicalTechnicians {
            get {
                return ResourceManager.GetString("MedicalTechnicians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naslov poruke.
        /// </summary>
        public static string MessageBoxTitle {
            get {
                return ResourceManager.GetString("MessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PON.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moj nalog.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv filter.
        /// </summary>
        public static string NameFilter {
            get {
                return ResourceManager.GetString("NameFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime i prezime.
        /// </summary>
        public static string NmaeSurname {
            get {
                return ResourceManager.GetString("NmaeSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nisu pronađeni termini.
        /// </summary>
        public static string NoAppointmentsFound {
            get {
                return ResourceManager.GetString("NoAppointmentsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaposleni nije pronađen..
        /// </summary>
        public static string NoEmployeesFound {
            get {
                return ResourceManager.GetString("NoEmployeesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nisu pronađeni pregledi..
        /// </summary>
        public static string NoExaminationsFound {
            get {
                return ResourceManager.GetString("NoExaminationsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niste selektovali stavku..
        /// </summary>
        public static string NoSelection {
            get {
                return ResourceManager.GetString("NoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne.
        /// </summary>
        public static string NoTooltip {
            get {
                return ResourceManager.GetString("NoTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkTooltip {
            get {
                return ResourceManager.GetString("OkTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacijent.
        /// </summary>
        public static string Patient {
            get {
                return ResourceManager.GetString("Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacijent dodan.
        /// </summary>
        public static string PatientAdded {
            get {
                return ResourceManager.GetString("PatientAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacijent pronađen.
        /// </summary>
        public static string PatientFound {
            get {
                return ResourceManager.GetString("PatientFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMBG Pacijenta.
        /// </summary>
        public static string PatientID {
            get {
                return ResourceManager.GetString("PatientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacije o pacijentu.
        /// </summary>
        public static string PatientInformation {
            get {
                return ResourceManager.GetString("PatientInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMBG Pacijenta.
        /// </summary>
        public static string PatientJMBG {
            get {
                return ResourceManager.GetString("PatientJMBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacijent nije pronađen..
        /// </summary>
        public static string PatientNotFound {
            get {
                return ResourceManager.GetString("PatientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacijenti.
        /// </summary>
        public static string Patients {
            get {
                return ResourceManager.GetString("Patients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacijent ažuriran..
        /// </summary>
        public static string PatientUpdated {
            get {
                return ResourceManager.GetString("PatientUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj telefona.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cijena.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cijena - rastuće.
        /// </summary>
        public static string PriceAscending {
            get {
                return ResourceManager.GetString("PriceAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cijena - opadajuće.
        /// </summary>
        public static string PriceDescending {
            get {
                return ResourceManager.GetString("PriceDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osvježi.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osvježen prikaz..
        /// </summary>
        public static string Refreshed {
            get {
                return ResourceManager.GetString("Refreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukloni sve filtere.
        /// </summary>
        public static string RemoveAllFilters {
            get {
                return ResourceManager.GetString("RemoveAllFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetuj.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uloga.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUB.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sačuvaj.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraži.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraga po JMBG.
        /// </summary>
        public static string SearchByID {
            get {
                return ResourceManager.GetString("SearchByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberi.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberi termin.
        /// </summary>
        public static string SelectAppointment {
            get {
                return ResourceManager.GetString("SelectAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selektujte račun.
        /// </summary>
        public static string SelectBillToView {
            get {
                return ResourceManager.GetString("SelectBillToView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selektujte medicinskog tehničara.
        /// </summary>
        public static string SelectMedicalTechnician {
            get {
                return ResourceManager.GetString("SelectMedicalTechnician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite ulogu.
        /// </summary>
        public static string SelectRole {
            get {
                return ResourceManager.GetString("SelectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srpski.
        /// </summary>
        public static string Serbian {
            get {
                return ResourceManager.GetString("Serbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavke.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaz materijala..
        /// </summary>
        public static string ShowingAllMaterials {
            get {
                return ResourceManager.GetString("ShowingAllMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijava.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortiraj.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortiraj.
        /// </summary>
        public static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uslov za sortiranje poništen..
        /// </summary>
        public static string SortCleared {
            get {
                return ResourceManager.GetString("SortCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortiano..
        /// </summary>
        public static string Sorted {
            get {
                return ResourceManager.GetString("Sorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specijalizacija.
        /// </summary>
        public static string Specialization {
            get {
                return ResourceManager.GetString("Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalihe.
        /// </summary>
        public static string StockFilter {
            get {
                return ResourceManager.GetString("StockFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno obrisano..
        /// </summary>
        public static string SuccessfullyDeleted {
            get {
                return ResourceManager.GetString("SuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspjeh.
        /// </summary>
        public static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dovoljne zalihe.
        /// </summary>
        public static string Sufficient {
            get {
                return ResourceManager.GetString("Sufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NED.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iznenađenje.
        /// </summary>
        public static string Surprise {
            get {
                return ResourceManager.GetString("Surprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ČET.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrijeme.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do datuma.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danas.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukupan iznos.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tretman dodan..
        /// </summary>
        public static string TreatmentAdded {
            get {
                return ResourceManager.GetString("TreatmentAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tretmani.
        /// </summary>
        public static string Treatments {
            get {
                return ResourceManager.GetString("Treatments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tretman ažuriran..
        /// </summary>
        public static string TreatmentUpdated {
            get {
                return ResourceManager.GetString("TreatmentUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTO.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuspješno brisanje..
        /// </summary>
        public static string UnsuccessfullyDeleted {
            get {
                return ResourceManager.GetString("UnsuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmijeni.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmijeni termin.
        /// </summary>
        public static string UpdateAppointment {
            get {
                return ResourceManager.GetString("UpdateAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ažuriraj pregled.
        /// </summary>
        public static string UpdateExaminationTitle {
            get {
                return ResourceManager.GetString("UpdateExaminationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ažuriraj materijal.
        /// </summary>
        public static string UpdateMaterialTitle {
            get {
                return ResourceManager.GetString("UpdateMaterialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ažuriraj pacijenta.
        /// </summary>
        public static string UpdatePatientTitle {
            get {
                return ResourceManager.GetString("UpdatePatientTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ažuriraj tretman.
        /// </summary>
        public static string UpdateTreatment {
            get {
                return ResourceManager.GetString("UpdateTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogledaj detalje.
        /// </summary>
        public static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upozorenje.
        /// </summary>
        public static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRI.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da.
        /// </summary>
        public static string YesTooltip {
            get {
                return ResourceManager.GetString("YesTooltip", resourceCulture);
            }
        }
    }
}
